[template]
src = "server.conf.tmpl"
dest = "/etc/openvpn/server.conf"
keys = [
  "/openvpn/compress/algorithm/",
  "/openvpn/compress/enable/",
  "/openvpn/device/",
  "/openvpn/domainname/",
  "/openvpn/key/dhsize/",
  "/openvpn/key/dir/",
  "/openvpn/loglevel/",
  "/openvpn/maxclients/",
  "/openvpn/process/group/",
  "/openvpn/process/user/",
  "/openvpn/protocol/",
  "/openvpn/server/enablecrl/",
  "/openvpn/server/iprange/",
  "/openvpn/tls/enable/",
  "/openvpn/tls/key/"
]
